apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: assisted-image-service
  name: assisted-image-service
  namespace: assisted-installer
spec:
  ports:
  - name: assisted-image-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: assisted-image-service
  type: LoadBalancer
  loadBalancerIP: 10.89.1.241
