apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-service
  name: assisted-service
  namespace: assisted-installer
spec:
  ports:
  - name: assisted-service
    port: 8090
  - name: assisted-service-http
    port: 8091
  selector:
    app: assisted-service

