apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/openshift-assisted/cluster-api-agent/releases/latest/download/bootstrap-components.yaml
  - https://github.com/openshift-assisted/cluster-api-agent/releases/latest/download/controlplane-components.yaml
patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: baseline
labels:
  - pairs:
      clusterctl.cluster.x-k8s.io: ""

