apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: assisted-installer
resources:
- ./crds
- ./rbac
- pvc.yaml
- ingress-cert.yaml
- assisted-service-configmap.yaml
- assisted-servicelocal-auth-secret.yaml
- assisted-service-secret.yaml
- postgres-secret.yaml
- assisted-service-deployment.yaml
- assisted-service-svc.yaml
images:
- name: quay.io/edge-infrastructure/assisted-service
  newTag: ocm-2.10
