apiVersion: apps/v1
kind: Deployment
metadata:
  name: assisted-image-service
  namespace: assisted-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assisted-image-service
  template:
    metadata:
      labels:
        app: assisted-image-service
    spec:
      containers:
      - env:
        - name: LISTEN_PORT
          value: '8080'
        - name: RHCOS_VERSIONS
          valueFrom:
            configMapKeyRef:
              key: OS_IMAGES
              name: assisted-service-config
        - name: ASSISTED_SERVICE_SCHEME
          value: http
        - name: ASSISTED_SERVICE_HOST
          value: assisted-service:8090
        - name: IMAGE_SERVICE_BASE_URL
          value: http://{{ .Values.ingress.host }}
        - name: ALLOWED_DOMAINS
          value: '*'
        image: {{ .Values.assistedImage.image.repository }}:{{ .Values.assistedImage.image.tag | default "latest" }}
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 30
        name: assisted-image-service
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
      serviceAccountName: assisted-service
