apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-service
  name: assisted-service
  namespace: assisted-installer
spec:
  ports:
  - name: assisted-service
    port: {{ .Values.assistedService.port }}
    protocol: TCP
    targetPort: {{ .Values.assistedService.port }}
  selector:
    app: assisted-service
status:
  loadBalancer: {}
