apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-image-service
  name: assisted-image-service
  namespace: assisted-installer
spec:
  ports:
  - name: assisted-image-service
    port: {{ .Values.assistedImage.port }} 
    protocol: TCP
    targetPort: {{ .Values.assistedImage.port }}
  selector:
    app: assisted-image-service
