apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: object-store
  name: object-store
  namespace: assisted-installer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
