kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assisted-service
  namespace: assisted-installer
subjects:
  - kind: ServiceAccount
    name: assisted-service
    namespace: assisted-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assisted-service

